services:
  main:
    build: .
    image: ayjchen/cc-exercise-2
    depends_on:
      - "mongodb"
    environment:
      - DATABASE_URI=mongodb://mongodb:27017
    ports:
      - "3030:3030"

  mongodb:
    image: mongo:7
    # volumes:
    #   - data/:data/db
    ports:
      - "27017:27017"